version: '2'
services:
  articledb:
    container_name: articledb
    image: postgres:9.5
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=tpns_article_db
    - POSTGRES_PASSWORD=tpns
    volumes:
    - ${HOME}/projects/tpns/data/article/pgdata:/var/lib/postgresql/data
    networks:
    - core_net
  userdb:
    container_name: userdb
    image: postgres:9.5
    ports:
    - 5433:5432
    environment:
    - POSTGRES_USER=tpns_user_db
    - POSTGRES_PASSWORD=tpns
    volumes:
    - ${HOME}/projects/tpns/data/user/pgdata:/var/lib/postgresql/data
    networks:
    - core_net
  admindb:
    container_name: admindb
    image: postgres:9.5
    ports:
    - 5434:5432
    environment:
    - POSTGRES_USER=tpns_admin_db
    - POSTGRES_PASSWORD=tpns
    volumes:
    - ${HOME}/projects/tpns/data/admin/pgdata:/var/lib/postgresql/data
    networks:
    - core_net
  userservice:
    container_name: userservice
    image: pzografos/tpns-user-service
    ports:
    - 8081:8080
    - 5006:5005
    environment:
    - USER_SERVER_PORT=8080
    - USER_DB_HOST=userdb
    - USER_DB_PORT=5432
    - USER_DB_USER=tpns_user_db
    - USER_DB_PASS=tpns
    env_file:
    - dev/user.env
    depends_on:
    - userdb
    networks:
    - core_net
  articleservice:
    container_name: articleservice
    image: pzografos/tpns-article-service
    ports:
    - 8080:8080
    - 5005:5005
    environment:
    - ARTICLE_SERVER_PORT=8080
    - ARTICLE_DB_HOST=articledb
    - ARTICLE_DB_PORT=5432
    - ARTICLE_DB_USER=tpns_article_db
    - ARTICLE_DB_PASS=tpns
    env_file:
    - dev/article.env
    depends_on:
    - articledb
    - userservice
    networks:
    - core_net
  adminservice:
    container_name: adminservice
    image: pzografos/tpns-admin-service
    ports:
    - 8082:8080
    - 5007:5005
    environment:
    - ADMIN_SERVER_PORT=8080
    - ADMIN_DB_HOST=admindb
    - ADMIN_DB_PORT=5432
    - ADMIN_DB_USER=tpns_admin_db
    - ADMIN_DB_PASS=tpns
    env_file:
    - dev/admin.env
    depends_on:
    - admindb
    networks:
    - core_net
  articleq:
    container_name: articleq
    image: webcenter/activemq
    ports:
    - 8161:8161
    - 61616:61616
    - 5672:5672
    - 61613:61613
    - 1883:1883
    - 61614:61614
    environment:
    - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
    - ACTIVEMQ_MIN_MEMORY=512
    - ACTIVEMQ_MAX_MEMORY=2048
    - ACTIVEMQ_ADMIN_LOGIN=admin
    - ACTIVEMQ_ADMIN_PASSWORD=admin
    - ACTIVEMQ_USER_LOGIN=user
    - ACTIVEMQ_USER_PASSWORD=user
    - ACTIVEMQ_STATIC_QUEUES=article_queue
    - ACTIVEMQ_OPTS=-Dorg.apache.activemq.SERIALIZABLE_PACKAGES="*"
    volumes:
    - ${HOME}/projects/tpns/data/admin/activemq/data:/data/activemq
    - ${HOME}/projects/tpns/data/admin/activemq/logs:/var/log/activemq
    networks:
    - core_net
  webapp:
    container_name: webapp
    image: pzografos/tpns-web-app
    ports:
    - 80:80
    depends_on:
    - articleservice
    - userservice
    volumes:
    - ${HOME}/Dev/tpns-core-services/tpns-web-app:/usr/share/nginx/html/tpns
    networks:
    - core_net
networks:
  core_net:
    driver: bridge